### ISSUE TITLE
Unfreezing procedures (update to decision at IETF 95)

### ISSUE THREAD

**Issue by stpeter** [ice-wg/trickle#2]
Open issue from Yokohama: what to do about unfreezing when one component doesn't have the same foundation as another? We need a proposal.

**Comment by stpeter** [comment]
Posted to the list: https://mailarchive.ietf.org/arch/msg/ice/leqUEJydZs1iA0ZSw6iJ8jQeiDQ

**Comment by pthatcherg** [comment]
Decision made at IETF 95 (https://www.ietf.org/proceedings/95/minutes/minutes-95-ice)

Unfreeze first thing that comes in based on ordering. If you get a second also unfreeze.  With multiple candidates on the same foundation, if a candidate that comes later in the order arrives first, unfreeze that candidate. If a candidate from earlier in the order arrives later, unfreeze that one too.

**Comment by pthatcherg** [comment]
By the way, Taylor found an issue with "highest wins", and we may need to change it to "signaled wins (prflx loses) and then highest wins" to avoid race conditions causing priorities to be wrong.

He's going to send a message to the list shortly.
