### ISSUE TITLE
Trickle ICE plus ICE restarts

### ISSUE THREAD

**Issue by stpeter** [ice-wg/trickle#3]
@emcho and @stpeter had an editors' discussion (see https://github.com/emcho/trickle-ice/issues/3) about how to specify the handling of ICE restarts in the context of Trickle ICE. One possible approach would be to send a new ufrag and pwd without triggering a full offer/answer exchange, because Trickle (and ICE itself) can be used with application protocols that are not tied to O/A. There is an SDP dependency on the a= line, but we've disengaged Trickle ICE from SDP, too. Also, if the sender doesn't include a media description then a new offer might not be necessary anyway. I'm hoping that @emcho can propose text...

**Comment by pthatcherg** [comment]
At IETF 95, there was support for explicitly indicating which ufrag/pwd the candidate applies to.  But the specifics are signaling-specific.  So perhaps we should just update the text to say "SHOULD be explicit" in some way.

https://www.ietf.org/proceedings/95/minutes/minutes-95-ice

**Comment by emcho** [comment]
I am fine also adding to the spec a sample way of labeling them (the way
Trickle for SIP does)

Emil

On Mon, Jun 27, 2016 at 10:11 AM, Peter Thatcher notifications@github.com
wrote:

> At IETF 95, there was support for explicitly indicating which ufrag/pwd
> the candidate applies to. But the specifics are signaling-specific. So
> perhaps we should just update the text to say "SHOULD be explicit" in some
> way.
> 
> https://www.ietf.org/proceedings/95/minutes/minutes-95-ice
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/ice-wg/trickle/issues/3#issuecomment-228775526, or mute
> the thread
> https://github.com/notifications/unsubscribe/ABu5u_4QaOCYDpFwyhrP2z_po1B-63ALks5qP-g2gaJpZM4G_AmE
> .

## 

https://jitsi.org

**Comment by pthatcherg** [comment]
By the way, this came up in the JSEP work recently, that with ICE restarts being roll-back-able, the explicit ufrag is really needed for edge cases there.  We think the right solution is using a ufrag on the JS object, _not_ on the SDP (since we also need to include it on the end of candidates message, and since it would look weird being duplicated in so many lines in the current remote description).

**Comment by pthatcherg** [comment]
It looks like we already have a paragraph that indicates an implementation should have an explicit ufrag (or other correlation).  Great!  So, I made a PR to add some examples:

https://github.com/ice-wg/trickle/pull/8

**Comment by emcho** [comment]
resolved
