### ISSUE TITLE
Make sure there is a clear recommendation to try to trickle in declarative order

### ISSUE THREAD

**Issue by pthatcherg** [ice-wg/trickle#9]
Emil asked for this at IETF 96.

**Comment by stpeter** [comment]
I didn't hear this in the recording but perhaps I missed it. Anyway, I'm happy for @emcho to address the issue. :-)

**Comment by pthatcherg** [comment]
It's around 26:14 :).

**Comment by stpeter** [comment]
@emcho thinks this is no longer relevant given some of the other changes that we've made...
